name: CI/CD Pipeline with GitHub Actions for K8S

on:
  push:
    branches: [ "master-webrtc-catchmind", "chatforyou_v2"]
#    branches: [ "master-webrtc-catchmind", "infra/cicd-test" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  deploy:
    name: Build And Deploy K8S
    environment: chatforyou-back-env # 환경 지정
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      K8S_NAMESPACE: chatforyou # Kubernetes 네임스페이스
      DEPLOYMENT_NAME: chatforyou-v03    # Deployment 이름

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Kubeconfig 설정
      - name: Configure Kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo "${KUBE_CONFIG}" | base64 --decode > ${HOME}/.kube/config
          export KUBECONFIG=${HOME}/.kube/config

      # 3. TIMESTAMP 생성 (한국 시간으로) && IMAGE_URI 로 이미지명:태크명 공통화
      # IMAGE_URI = chatforyou-io/chatforyou-io-backend:시간
      - name: Generate TIMESTAMP in KST
        id: timestamp
        run: |
          export TZ=Asia/Seoul
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "IMAGE_URI=ghcr.io/sejonj/chatforyou:$TIMESTAMP" >> $GITHUB_ENV

      # 5. Docker 이미지 빌드 및 태그
      - name: Build Docker Image
        run: |
          docker build --file Dockerfile -t $IMAGE_URI .

      # 6. Docker 이미지 푸시 (GitHub Container Registry)
      - name: Push Docker Image to GitHub Packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_URI

      # 7. Kubernetes 배포
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
            chatforyou-container=$IMAGE_URI \
            -n $K8S_NAMESPACE
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE

      # 프론트엔드 환경 변수 설정
      - name: Set Frontend Vars
        run: |
          echo "FRONT_DEPLOYMENT_NAME=chatforyou-frontend-v03" >> $GITHUB_ENV
          echo "FRONT_IMAGE_URI=ghcr.io/sejonj/chatforyou-frontend:$TIMESTAMP" >> $GITHUB_ENV

      # 프론트엔드 Docker 이미지 빌드
      - name: Build Frontend Docker Image
        run: |
          cd nodejs-frontend
          docker build -t $FRONT_IMAGE_URI .
          cd ..

      # 프론트엔드 Docker 이미지 푸시
      - name: Push Frontend Docker Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $FRONT_IMAGE_URI

      # 프론트엔드 Kubernetes 배포
      - name: Deploy Frontend to Kubernetes
        run: |
          kubectl set image deployment/$FRONT_DEPLOYMENT_NAME \
            chatforyou-frontend-container=$FRONT_IMAGE_URI \
            -n $K8S_NAMESPACE
          kubectl rollout status deployment/$FRONT_DEPLOYMENT_NAME -n $K8S_NAMESPACE